### ISSUE TITLE
Error in gcc-wrapper.py when installing ZFS-DKMS

### ISSUE THREAD

**Issue by ViRb3** [ayufan-rock64/linux-build#323]
When installing the ZFS/SPL module, I get the following error:
```
Error! Bad return status for module build on kernel: 4.4.154-1128-rockchip-ayufan-g61b4b1151f9a (aarch64)
Consult /var/lib/dkms/spl/0.7.5/build/make.log for more information.
```

The makefile log reads this:
```
Making all in module
make[2]: Entering directory '/var/lib/dkms/spl/0.7.5/build/module'
make -C /lib/modules/4.4.154-1128-rockchip-ayufan-g61b4b1151f9a/build SUBDIRS=`pwd`  CONFIG_SPL=m modules
make[3]: Entering directory '/usr/src/linux-headers-4.4.154-1128-rockchip-ayufan-g61b4b1151f9a'
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/spl/spl-proc.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/splat/splat-ctl.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/spl/spl-kmem.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/splat/splat-kmem.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/spl/spl-kmem-cache.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/splat/splat-taskq.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/spl/spl-vmem.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/spl/spl-thread.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/spl/spl-taskq.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/splat/splat-random.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/spl/spl-rwlock.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/spl/spl-vnode.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/splat/splat-mutex.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/splat/splat-condvar.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/spl/spl-err.o
  CC [M]  /var/lib/dkms/spl/0.7.5/build/module/spl/spl-kobj.o
Traceback (most recent call last):
  File "./scripts/gcc-wrapper.py", line 115, in <module>
    status = run_gcc()
  File "./scripts/gcc-wrapper.py", line 98, in run_gcc
    print (line.decode("utf-8"), end="")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 66: ordinal not in range(128)
scripts/Makefile.build:277: recipe for target '/var/lib/dkms/spl/0.7.5/build/module/spl/spl-vnode.o' failed
```

Any suggestions what is wrong?

**Comment by ViRb3** [comment]
Related commit: https://github.com/ayufan-rock64/linux-kernel/commit/c3714cbbcfbf0f72179e611ee16bf040f5b1695d
